{ inputs, config, lib, pkgs, modulesPath, ... }:
{
      boot.kernelPackages = with pkgs; let
      customKernelPackages = linuxPackagesFor (linuxPackages_lqx.kernel.override {                                              
      structuredExtraConfig = with lib.kernel; {
         VIRTIO_MMIO = yes;
         SCHED_CFS = yes;
         NET_SCH_CAKE = yes;
         ZFS = no;
         MNATIVE_INTEL = yes;
         MAXSMP = yes;
         MTRR = yes;
         X86_MCE_INTEL = yes;
         MICROCODE_INTEL = yes;
         CPU_FREQ_GOV_PERFORMANCE = yes;
         TRANSPARENT_HUGEPAGE = yes;
         TRANSPARENT_HUGEPAGE_MADVISE = yes;
         X86_INTEL_TSX_MODE_ON = yes;
         SPECULATION_MITIGATIONS = no;
         CPU_IBRS_ENTRY = no;
         CPU_IBPB_ENTRY = no;
       };
     ignoreConfigErrors = true;
    });
    in customKernelPackages;
  boot.kernelPatches = [
   { patch = builtins.fetchurl "https://github.com/clearlinux-pkgs/linux/raw/main/0001-powerbump-functionality.patch";}
   { patch = builtins.fetchurl "https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.3/0002-mm-Support-soft-dirty-flag-read-with-reset.patch";}
   { patch = builtins.fetchurl "https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.3/0012-misc-additions.patch";}
   { patch = builtins.fetchurl "https://github.com/Frogging-Family/linux-tkg/raw/master/linux-tkg-patches/6.3/0013-optimize_harder_O3.patch";}
  ];

  powerManagement = {
  enable = false;
  cpuFreqGovernor = lib.mkDefault "performance";
 };
    system.requiredKernelConfig = with config.lib.kernelConfig; [
        (isYes "CC_OPTIMIZE_FOR_PERFORMANCE")
        (isYes "MNATIVE_INTEL")
        (isYes "SCHED_BMQ")
        (isYes "ac97_bus")
        (isYes "acpi_pad")
        (isYes "acpi_tad")
        (isYes "amdgpu")
        (isYes "apple_mfi_fastcharge")
        (isYes "asus_wmi")
        (isYes "auth_rpcgss")
        (isYes "cec")
        (isYes "coretemp")
        (isYes "crc32c_intel")
        (isYes "crc32_pclmul")
        (isYes "crct10dif_pclmul")
        (isYes "dns_resolver")
        (isYes "drm_buddy")
        (isYes "drm_display_helper")
        (isYes "drm_kms_helper")
        (isYes "drm_ttm_helper")
        (isYes "ee1004")
        (isYes "eeepc_wmi")
        (isYes "exfat")
        (isYes "fat")
        (isYes "fscache")
        (isYes "fuse")
        (isYes "ghash_clmulni_intel")
        (isYes "gpu_sched")
        (isYes "grace")
        (isYes "i2c_dev")
        (isYes "i2c_i801")
        (isYes "i2c_smbus")
        (isYes "idma64")
        (isYes "intel_cstate")
        (isYes "intel_pmc_bxt")
        (isYes "intel_powerclamp")
        (isYes "intel_rapl_common")
        (isYes "intel_rapl_msr")
        (isYes "intel_tcc_cooling")
        (isYes "intel_uncore")
        (isYes "intel_vsec")
        (isYes "iommu_v2")
        (isYes "ip6_tables")
        (isYes "ip_set")
        (isYes "ip_tables")
        (isYes "irqbypass")
        (isYes "iTCO_vendor_support")
        (isYes "iTCO_wdt")
        (isYes "joydev")
        (isYes "kvm")
        (isYes "kvm_intel")
        (isYes "ledtrig_audio")
        (isYes "lockd")
        (isYes "mc")
        (isYes "mei")
        (isYes "mei_me")
        (isYes "netfs")
        (isYes "nf_conntrack")
        (isYes "nf_conntrack_broadcast")
        (isYes "nf_conntrack_netbios_ns")
        (isYes "nf_defrag_ipv4")
        (isYes "nf_defrag_ipv6")
        (isYes "nf_nat")
        (isYes "nfnetlink")
        (isYes "nf_reject_ipv4")
        (isYes "nf_reject_ipv6")
        (isYes "nfs")
        (isYes "nfsv4")
        (isYes "nf_tables")
        (isYes "nft_chain_nat")
        (isYes "nft_ct")
        (isYes "nft_fib")
        (isYes "nft_fib_inet")
        (isYes "nft_fib_ipv4")
        (isYes "nft_fib_ipv6")
        (isYes "nft_objref")
        (isYes "nft_reject")
        (isYes "nft_reject_inet")
        (isYes "nvme")
        (isYes "nvme_common")
        (isYes "nvme_core")
        (isYes "pinctrl_alderlake")
        (isYes "platform_profile")
        (isYes "pmt_class")
        (isYes "pmt_telemetry")
        (isYes "polyval_clmulni")
        (isYes "polyval_generic")
        (isYes "qrtr")
        (isYes "r8169")
        (isYes "rfkill")
        (isYes "rpcsec_gss_krb5")
        (isYes "snd")
        (isYes "snd_compress")
        (isYes "snd_hda_codec")
        (isYes "snd_hda_codec_generic")
        (isYes "snd_hda_codec_hdmi")
        (isYes "snd_hda_codec_realtek")
        (isYes "snd_hda_core")
        (isYes "snd_hda_ext_core")
        (isYes "snd_hda_intel")
        (isYes "snd_hrtimer")
        (isYes "snd_hwdep")
        (isYes "snd_intel_dspcfg")
        (isYes "snd_intel_sdw_acpi")
        (isYes "snd_pcm")
        (isYes "snd_pcm_dmaengine")
        (isYes "snd_rawmidi")
        (isYes "snd_seq")
        (isYes "snd_seq_device")
        (isYes "snd_seq_dummy")
        (isYes "snd_soc_acpi")
        (isYes "snd_soc_acpi_intel_match")
        (isYes "snd_soc_core")
        (isYes "snd_soc_hdac_hda")
        (isYes "snd_sof")
        (isYes "snd_sof_intel_hda")
        (isYes "snd_sof_intel_hda_common")
        (isYes "snd_sof_pci")
        (isYes "snd_sof_pci_intel_tgl")
        (isYes "snd_sof_utils")
        (isYes "snd_sof_xtensa_dsp")
        (isYes "snd_timer")
        (isYes "snd_usb_audio")
        (isYes "snd_usbmidi_lib")
        (isYes "soundcore")
        (isYes "soundwire_bus")
        (isYes "soundwire_cadence")
        (isYes "soundwire_generic_allocation")
        (isYes "soundwire_intel")
        (isYes "sparse_keymap")
        (isYes "sunrpc")
        (isYes "tls")
        (isYes "ttm")
        (isYes "uas")
        (isYes "uinput")
        (isYes "usb_storage")
        (isYes "uvcvideo")
        (isYes "vfat")
        (isYes "video")
        (isYes "videobuf2_common")
        (isYes "videobuf2_memops")
        (isYes "videobuf2_v4l2")
        (isYes "videobuf2_vmalloc")
        (isYes "videodev")
        (isYes "vmd")
        (isYes "wmi")
        (isYes "wmi_bmof")
        (isYes "x86_pkg_temp_thermal")
        (isYes "zram")
        (isYes "EFI")
        (isEnabled "DRM_AMDGPU_SI")
        (isYes "PCI_DIRECT")
        (isYes "PCI_MMCONFIG")
        (isEnabled "UIO_IVSHMEM")
        (isEnabled "DRM_VIRTIO_GPU")
        (isYes "PCI_HOST_GENERIC")
        (isYes "VIRTIO_PCI_LIB")
        (isYes "VIRTIO_MENU")
        (isYes "PCI_HOST_COMMON")
        (isEnabled "VIRTIO_BLK")
        (isEnabled "VIRTIO_PCI")
        (isEnabled "VIRTIO_NET")
        (isEnabled "EXT4_FS")
        (isEnabled "NET_9P_VIRTIO")
        (isEnabled "9P_FS")
        (isYes "BLK_DEV")
        (isYes "PCI")
        (isYes "NETDEVICES")
        (isYes "NET_CORE")
        (isYes "INET")
        (isYes "FUTEX")
        (isYes "FUTEX_PI")
        (isYes "TICK_ONESHOT")
        (isYes "NO_HZ_COMMON")
        (isYes "NO_HZ_FULL")
        (isYes "CONTEXT_TRACKING_USER")
        (isYes "NO_HZ")
        (isYes "HIGH_RES_TIMERS")
        (isYes "CLOCKSOURCE_WATCHDOG_MAX_SKEW_US")
        (isYes "BPF")
        (isYes "HAVE_EBPF_JIT")
        (isYes "ARCH_WANT_DEFAULT_BPF_JIT")
        (isYes "BPF_SYSCALL")
        (isYes "BPF_JIT")
        (isYes "BPF_JIT_ALWAYS_ON")
        (isYes "BPF_JIT_DEFAULT_ON")
        (isYes "BPF_UNPRIV_DEFAULT_OFF")
        (isYes "USERMODE_DRIVER")
        (isYes "BPF_LSM")
        (isYes "PREEMPT_VOLUNTARY_BUILD")
        (isYes "PREEMPT_VOLUNTARY")
        (isYes "SCHED_CORE")
        (isYes "NETWORK_FILESYSTEMS")
      ] ++ optionals (!cfg.graphics) [
        (isYes "SERIAL_8250_CONSOLE")
        (isYes "SERIAL_8250")
      ] ++ optionals (cfg.writableStore) [
      (isEnabled "OVERLAY_FS")
      (isYes "MTRR")
      (isYes "X86_MCE_INTEL")
      (isYes "MICROCODE_INTEL")
      (isYes "CPU_FREQ_GOV_PERFORMANCE")
      (isYes "TRANSPARENT_HUGEPAGE")
      (isYes "TRANSPARENT_HUGEPAGE_MADVISE")
      (isYes "MAXSMP")
    ];
}
